sudo: required
services:
  - docker
before_install:
  - docker build -t andreagotta/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run andreagotta/react-test npm test -- --coverage

after_success:
  - docker build -t andreagotta/multi-client ./client
  - docker build -t andreagotta/multi-nginx ./nginx
  - docker build -t andreagotta/multi-server ./server
  - docker build -t andreagotta/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push andreagotta/multi-client
  - docker push andreagotta/multi-nginx
  - docker push andreagotta/multi-server
  - docker push andreagotta/multi-worker
